### ISSUE TITLE
BluetoothGattCharacteristic needed to extract value on subscription

### ISSUE THREAD

**Issue by truizlop** [inovait/neatle#21]
First of all, I'd like to thank you for your contribution, it has been very easy to integrate and works very well so far.

I have a problem though. I'm pairing with a Heart Rate Monitor and this is the code I was using to extract the heart rate value from the `BluetoothGattCharacteristic` from the Android framework class:

``` java
int flag = characteristic.getProperties();
int format = (flag & 0x01) != 0 ?
                BluetoothGattCharacteristic.FORMAT_UINT16 :
                BluetoothGattCharacteristic.FORMAT_UINT8;
int heartRate = characteristic.getIntValue(format, 1);
```

However, when I receive a `CommandChange` on a subscription now, I don't have access to either the properties of the characteristic, or the characteristic itself, so I cannot extract the heart rate.

How should I proceed here? If it is not even possible with the current state of the library and its code needs to be modified, I can implement the necessary modifications if you provide some guidance.

**Comment by truizlop** [comment]
By inspecting how `CommandResult` is [created](https://github.com/inovait/neatle/blob/master/neatle/src/main/java/si/inova/neatle/operation/CommandResult.java#L164), I think it is not possible to do what I want to do. It should hold the `BluetoothGattCharacteristic`.

**Comment by tomazs** [comment]
Fixed merged into master.

**Comment by mihakrajnc** [comment]
A new release containing the changes has been published.

```groovy
compile 'si.inova:neatle:0.9.3'
```
