### ISSUE TITLE
How to read & write sequentially with chained results?

### ISSUE THREAD

**Issue by ruckus** [inovait/neatle#30]
Thanks for this library.

I'm attempting to perform a read and then I want to perform a write based on the result of the read - I thought I could use the `OperationBuilder` for this but its not clear on how to use it in such a style.

Does the `OperationBuilder` support this style of use? And if so, how? 

Thanks!

**Comment by tomazs** [comment]
Currently you have two options:

You start a new operation, which you execute after you get read results. 
```java
Operation operation = Neatle.createOperationBuilder(context)
        .read(SERVICE_UUID, TARGET_UUID)
        .onFinished(new SimpleOperationObserver() {
            @Override
            public void onOperationFinished(Operation op, OperationResults results) {
                if(results.wasSuccessful()){
                       Neatle.createOperationBuilder(context).write(SERVICE_UUID, WRITE_CHAR_UUID).execute(...)
                }
            }
        })
        .build(device);
operation.execute();
```

Or create you own _InputSource_ and "lazy" evaluates what to write.

```java
MyInputSource  src = new InputSource() {
     int readValue = 0;
     void open() throws IOException {} // nothing to do
     void close() throws IOException {} // nothing to do
 
     byte[] nextChunk() throws IOException {
        if (readValue == SOMETHING) {
            return byte[] { 0x2, 0x3}
          }
     }
};

**Comment by ruckus** [comment]
Hi @tomazs thank you for the response. The lazy approach sounds interesting; I'm having a hard time seeing how that would work though, since you need the input from the `.read` operation. Perhaps you could flesh out a more concrete example? Thank you!

**Comment by ruckus** [comment]
Oh, I think by lazy you mean to use the `.read(UUID, characteristicsUUID, CommandObserver)` signature, and in the `CommandObserver` you read the result and set it to a variable which a moment later the `.write()` input source can pick up...

**Comment by tomazs** [comment]
@ruckus that is what I had in mind. It's not the most elegant solution but it should work. In the future we plan to support nested commands to support this scenario out of the box.
