### ISSUE TITLE
Example: create an write operation

### ISSUE THREAD

**Issue by Shunwei** [inovait/neatle#38]
Hey, at first thx for your work!
second: can you add an example in wiki with WRITE-OPERATION?
I'm an newbie android developer, and I'm trying to write some bytes(like 0x11) to my BLE device, I can't get further without examples.

**Comment by tomazs** [comment]
@matejdro can you please add a write example to the Readme file.

**Comment by Shunwei** [comment]
OK, I write some code, and it works:
`.        val ledService:UUID = UUID.fromString("MY_UUID_SERVICE")
            val ledCharac:UUID = UUID.fromString("MY_UUID_CHARACTERISTIC")
            val byteArr = byteArrayOf(0x11)
            val test:InputSource = ByteArrayInputSource(byteArr)
            val operation: Operation = Neatle.createOperationBuilder(context)
                    .write(ledService, ledCharac, test)
                    .onFinished(object: SimpleOperationObserver(){

                        @Override
                        override fun onOperationFinished(op: Operation, results: OperationResults){
                            if(results.wasSuccessful()){
                                //TODO
                            } else {
                                //TODO
                            }
                        }
                    })
                    .build(Neatle.getDevice("00:11:22:33:44:55"))
            operation.execute()`
