### ISSUE TITLE
Neatle: Command failed. Aborting operation. Error: 257

### ISSUE THREAD

**Issue by youbinrocks** [inovait/neatle#42]
i'm using Neatle operation to write characteristic, if I put  InputSource to StringInputSource("100")  like code below,  i was excepting to get chaged major to 100 but i get 257 error

**code for operation**
~~~
final Operation operation = Neatle.createOperationBuilder(this)
                    .write(SERVICE_UUID_USERDATA,CHARACTERISTIC_UUID_MAJOR, new StringInputSource("100"))
                    .onFinished(new SimpleOperationObserver() {
                        @Override
                        public void onOperationFinished(Operation op, OperationResults results) {
                            Log.i(TAG, "onOperationFinished: op: " + op.toString());
                            Log.i(TAG, "onOperationFinished: result: " + results.toString());
                            Log.i(TAG, "onOperationFinished: ");
                            if(results.wasSuccessful()){
                                Log.i(TAG, "onOperationFinished: success");
                                Log.i(TAG, "onOperationFinished: result: " + results);
                            }else {
                                Log.i(TAG, "onOperationFinished: fail");
                            }
                        }
                    })
                    .build(Neatle.getDevice(mSelectedBeacon.getMac()));
            operation.execute();
~~~

 **log for error**

 Connection attempt failed. Notifying all pending operations
    OperationImpl: onConnectionStateChange, state:133, newState: 0
04-26 19:58:38.652 3955-3955I/Neatle: Command failed. Aborting operation. Error: 257
04-26 19:58:38.654 3955-3955/EditBeaconActivity: onOperationFinished: op: Operation[retryCount: 0, attempts: 0, commands:[WriteCommand[async:false -"characteristicUUID"] on [serviceUUID]]]
04-26 19:58:38.655 3955-3955/EditBeaconActivity: onOperationFinished: result: si.inova.neatle.operation.OperationResults@2216ffb

is there someting i missed?

**Comment by tomazs** [comment]
For some reason the connection cannot established. Error 133 is a general error and usually means that the device is no reachable. 
Are you able to connect to the beacon?

Can you paste all the logs?

**Comment by youbinrocks** [comment]
My mistake , i found out that my app disconnect right after connecting to beacon.  
after connecting it work. tks
