### ISSUE TITLE
ByteArrayInputSource MAX_CHUNK_SIZE isn't configurable

### ISSUE THREAD

**Issue by mmert1988** [inovait/neatle#49]
Once I tried to transport some bigger data (small JSON payload, e.g. wifi credentials) I found out, that the data isn't transported completely via a write operation. After a small investigation of your code, I've found out that the `MAX_CHUNK_SIZE` in your `ByteArrayInputSource` class is hardcoded set to `20` causing the problem. I would be great, that you provide an option to make it configurable in the client code in the newer versions.

**Comment by tomazs** [comment]
BLE only allows you transfer maximum is 20 bytes per operation so even if we would make it configurable it would not help you much.

That said neatle will break larger payload into "chunks" and transfer them. For example the code bellow will write 1024 bytes to a characteristic.

```
byte[] dataToWrite = new byte[1024]
InputSource inputSource = new ByteArrayInputSource(dataToWrite);

Operation operation = Neatle.createOperationBuilder(context)
        .write(serviceToWrite, characteristicToWrite, inputSource)
        .onFinished(new SimpleOperationObserver() {
            @Override
            public void onOperationFinished(Operation op, OperationResults results) {
                if (results.wasSuccessful()) {
                    System.out.println("Write was successful!");
                } else {
                    System.out.println("Write failed! ");
                }
            }
        })
        .build(device);
operation.execute();
```
