### ISSUE TITLE
GPS required on devices running S+

### ISSUE THREAD

**Issue by behelit** [inovait/neatle#61]
Android 12 does not require GPS to be turned on when scanning for devices using the BLUETOOTH_CONNECT/BLUETOOTH_SCAN permissions.
It seems that it will not scan unless I turn it on, even tho there's no errors logged.

**Comment by tomazs** [comment]
@matejdro please take a look at this

**Comment by matejdro** [comment]
Whole situation regarding those permissions seems weird.

Android 12 does not require location permission, but it still seems to require location services on to scan for devices. Also note that to scan for some devices (such as beacons), you still need location permission despite new BLUETOOTH_SCAN permission.

**Comment by behelit** [comment]
I was able to work out the difference as to why your library didn't work while my own code did.
It turns out that omitting the 'neverForLocation' flag on the BLUETOOTH_SCAN permission, will treat it as a location request.
Adding the flag will allow the scan to work correctly without location permissions nor GPS being enabled.

```
<uses-permission android:name="android.permission.BLUETOOTH_SCAN"
        android:usesPermissionFlags="neverForLocation"/>
```
